# Generated by Django 3.2.9 on 2021-12-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfilio', '0002_auto_20211205_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='small_about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
