# Generated by Django 3.2.9 on 2021-12-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfilio', '0005_portfolio_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
